### ISSUE TITLE
webpage and css?

### ISSUE THREAD

**Issue by irenevlachou** [Nikallettt/Nikallettt.github.io#1]
can you please upload your codepen?

**Comment by Nikallettt** [comment]
How?

**Comment by Nikallettt** [comment]
We can’t come to the presentation today, because we are feeling super bad
for some reason...Can we send you what we did in a couple of days?

**Comment by irenevlachou** [comment]
It will be great if you can now export the zip from Codepen (bottom right button), then (from the “dist” folder) upload index.html and style.css to Github. Don’t forget to commit the changes with the green button!

**Comment by Nikallettt** [comment]
I uploaded. But we also couldn’t type the letters in which we have icons
for some reason.... idk how to fix that...

**Comment by irenevlachou** [comment]
ok, can you also upload the .glyphs file?

**Comment by Nikallettt** [comment]
uploaded
